
export const FILTER = Object.freeze({
    INTERVIEW_RATING_GREATER_THAN_3: "INTERVIEW_RATING_GREATER_THAN_3",
    COOP_RATING_GREATER_THAN_3: "COOP_RATING_GREATER_THAN_3",
    SALARY_GREATER_THAN_40 : "SALARY_GREATER_THAN_40"
  });
  